<?php

namespace Gmsantos;

use Illuminate\Support\Collection;

class Inspiring
{
    /**
     * Get a funny inspiring quote.
     *
     * I've made this commit from my desk.
     *
     * Quotes source: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/246c8bd1684f89d1e3c87a77148bc51e6555f83c/PowerEditor/src/Notepad_plus.cpp#L5500
     *
     * @return string
     */
    public static function quote()
    {
        return Collection::make([
            
            " As lágrimas do Chuck Norris curam o câncer. É uma pena que ele não chore nunca.",
            "Chuck Norris não dorme. Ele espera.",
            "Chuck Norris está processando a NBC. Ele alega que \"Lei e Ordem\" são os nomes patenteados para suas pernas esquerda e direita. ",
            "Se você pode ver Chuck Norris, ele pode ver você. Se não pode ver Chuck Norris, você pode estar perto da morte.",
            "Chuck Norris contou até o infinito. Duas vezes.",
            "A última página do Guiness diz em letras miúdas: \"Todos os recordes do mundo pertencem a Chuck Norris. Nós apenas nos damos o trabalho de listar os segundos colocados em cada categoria.\"",
            "A Grande Muralha da China foi originalmente construída pra impedir a entrada de Chuck Norris naquele país. Ela falhou miseravelmente.",
            "Se você perguntar ao Chuck Norris que horas são, ele sempre dirá, \"Dois segundos até...\". Depois de você perguntar \"Dois segundos até o quê?\", ele dará um roundhouse kick na sua cara.",
            "Chuck Norris vendeu sua alma ao diabo para ter seu visual bacana e suas habilidades incomparáveis de artes marciais. Pouco tempo depois da transação terminar, Chuck Norris deu um roundhouse kick na cara do diabo e pegou sua alma de volta. O diabo, que aprecia ironia, não conseguiu ficar bravo e admitiu que deveria ter previsto isso. Eles agora jogam poker todas as segundas quartas-feiras de cada mês.",
            "Chuck Norris uma vez comeu 72 Kg de carne em uma hora. Ele passou os primeiros 45 minutos fazendo sexo com a garçonete.",
            "Quando Chuck Norris recebe os impostos, ele manda de volta folhas brancas com uma foto dele agachado, pronto para atacar. Chuck Norris não teve que pagar impostos nunca. Nunca!",
            "Chuck Norris era um dos personagens originais do jogo \"Street Fighter II\". Ele só foi removido porque todos os botões faziam ele dar um roundhouse kick. Quando perguntaram sobre essa falha do jogo, Chuck Norris respondeu: \"Que falha do jogo?\"",
            "Chuck Norris pediu um Big Mac no Bob's. Ele foi atendido.",
            "Uma vez Chuck Norris comeu um bolo inteiro antes que seus amigos pudessem lhe contar que havia uma stripper dentro.",
            "Wilt Chamberlein declarou já ter dormido com mais de 20.000 mulheres em toda sua vida. Chuck Norris chama isso de uma \"terça-feira monótona\".",
            "Quando Deus disse \"Que se faça a luz!\", Chuck Norris falou \"Diga 'por favor'.\"",
            "Uma vez Chuck Norris desceu a rua com uma ereção massiva. Não houve sobreviventes.",
            "Chuck Norris tem duas velocidades: Andar e Matar.",
            "Chuck Norris não lê livros, ele os encara até conseguir toda a informação que precisa.",
            "Chuck Norris joga roleta russa com uma arma inteiramente carregada, e ganha.",
            "Chuck Norris não não tem um forno ou microondas, pois, como todo mundo sabe, \"a vingança é um prato que se come frio.\"",
            "Algumas pessoas usam uniforme do Superman, mas ninguém se atreve a usar uniforme de Chuck Norris.",
            "Não existe queixo por trás da barba de Chuck Norris, apenas outro punho.",
            "Chuck Norris só dorme de luz acesa. Não, Chuck Norris não tem medo do escuro, mas a recíproca não é verdadeira.",
            "Certa vez Chuck Norris deu um roundhouse kick tão rápido que quebrou a velocidade da luz, voltou no tempo e atingiu um navio chamado Titanic.",
            "Uma vez Chuck Norris desafiou o ciclista Lance Armstrong para ver quem tinha mais testículos. Chuck Norris ganhou por 5.",
            "Armas não matam. O que mata é Chuck Norris.",
            "Chuck Norris uma vez tomou um vidro inteiro de pílulas para dormir. Elas fizeram ele piscar.",
            "Chuck Norris é a razão por que o Wally (do livro \"Onde está Wally?\") se esconde.",
            "Chuck Norris pode dividir por zero.",
            "Hiroshima e Nagasaki nunca viram uma bomba atômica. Chuck Norris comeu um sushi estragado e deu um arroto por lá. Foi só isso.",
            "Cientistas estimaram que a explosão de uma galáxia libera energia equivalente a 1 CNRhK. Ou seja, um Chuck Norris's Roundhouse Kick.",
            "Chuck Norris pode tocar no MC Hammer (autor da música \"U Can't Touch This\"",
            "Quando Chuck Norris faz flexões, ele não levanta o próprio peso. Ele empurra o planeta.",
            "Chuck Norris venceu o Campeonato Mundial de Poker com um dois de paus e uma carta \"Saída Livre da Prisão\" do Banco Imobiliário.",
            "Deus precisava de 10 dias para construir o mundo. Chuck Norris deu a ele 6 e olhe lá.",
            "Ozzy Osbourne morde cabeças de morcegos. Chuck Norris morde cabeças de tigres siberianos.",
            "O título original para Star Wars era \"Skywalker: Texas Ranger\", estrelando Chuck Norris.",
            "Chuck Norris recusou o papel porque se ele usasse \"a força\", Darth Vader falaria fino para o resto da vida.",
            "Chuk Norris não tem casa. Ele escolhe uma casa e seus moradores se mudam.",
            "Os dinossauros olharam torto para Chuck Norris uma vez. Uma vez.",
            "Quando o Bicho Papão vai dormir, ele deixa a luz acesa com medo de Chuck Norris.",
            "Se você errar algum dia, obviamente você não é Chuck Norris.",
            "Se Chuck Norris se atrasar, é melhor o tempo andar mais devagar.",
            "Chuck Norris perdeu a virgindade antes do pai.",
            "Antes de esquecer um presente de Chuck Norris, Papai Noel existia.",
            "Uma imagem vale mais que mil palavras. Chuck Norris vale mais que um milhão de imagens.",
            "Chuck Norris não compra manteiga. Ele dá roundhouse kicks nas vacas e elas viram manteiga.",
            "Quando urina, Chuck Norris pode facilmente perfurar titânio.",
            "Chuck Norris não faz a barba, ele dá um roundhouse kick na própria cara. Afinal, a única coisa que pode cortar Chuck Norris é Chuck Norris.",
            "As Tartarugas Ninja são baseadas numa história real. Uma vez Chuck Norris estava mascando um casco de tartaruga (ele adora!) e, quando foi ao banheiro, fez uma tartaruga falante de 1,80m que sabia caratê.",
            "Chuck Norris inventou a cesariana quando deu um roundhouse kick para sair da barriga de sua mãe.",
            "Para algumas pessoas, o testículo esquerdo é maior que o direito. Para Chuck Norris, cada testículo é maior que o outro.",
            "Ao responder as questãoes de uma prova, escreva sempre \"Chuck Norris\". Você vai sempre tirar nota 10.",
            "Chuck Norris inventou o preto. Na verdade, ele inventou todas as cores conhecidas. Exceto o rosa. Tom Cruise inventou essa.",
            "Chuck Norris tem 12 luas. Uma deles se chama Terra.",
            "Chuck Norris não tem cafeteira. Ele mói café com os dentes e ferve a água com sua fúria.",
            "Se você procurar no Google por \"Chuck Norris levando uma surra\", não encontrará nenhum documento correspondente. É claro. Isso nunca aconteceu.",
            "Chuck Norris leva vinte minutos para passar uma hora.",
            "O Triângulo das Bermundas era um quadrado até Chuck Norris dar um roundhouse kick em um dos cantos.",
            "Chuck Norris não acredita em duendes.",
            "Se \"O Exterminador do Futuro\" fosse com Chuck Norris, ele seria um documentário.",
            "Uma vez um urso atravessou o caminho de Chuck Norris. O trauma foi tão grande que o animal fugiu para o Ártico e ficou cheio de cabelos brancos. Surgiu então o urso-polar.",
            "Quando bate palmas, Chuck Norris pode transformar carvão em diamantes. E vice-versa.",
            "Chuck Norris inventou o sexo, as drogas e o rock n' roll. Nessa ordem.",
            "A maioria das pessoas tem 23 pares de cromossomos. Chuck Norris tem 72. Todos venenosos.",
            "Não existem armas de destruição em massa no Iraque. Chuck Norris mora em Oklahoma.",
            "Um estudo revelou que as três maiores causas de morte nos Estados Unidos são: infartos, câncer e Chuck Norris. Não necessariamente nessa ordem.",
            "Chuck Norris recentemente teve a idéia de vender sua urina enlatada. Chama-se \"Red Bull\"",
            "98% das mulheres americanas perderam sua virgindade com Chuck Norris. 2% das mulheres americanas são da família Norris.",
            "O nome original da Bíblia era \"Chuck Norris and Friends\"",
            "Chuck Norris inventou a internet. Tudo para guardar seu acervo pornográfico.",
            "Quando Bruce Banner fica irado, ele se transforma no Hulk. Quando o Hulk fica irado, ele se transforma em Chuck Norris.",
            "O título original de \"Alien vs. Predador\" era \"Alien e Predador vs. Chuck Norris\". O filme foi cancelado porque ninguém pagaria para ver um filme de 14 segundos.",
            "Chuck Norris não usa relógio. Ele decide que horas são.",
            "70% do corpo humano é água. 70% do corpo de Chuck Norris é seu pênis.",
            "Papel vence pedra, pedra vence tesoura e tesoura vence papel. Chuck Norris vence os três. Ao mesmo tempo.",
            "Chuck Norris entrou para o Clube da Luta. O Clube perdeu.",
            "Quando Chuck Norris joga War, George Bush se esconde debaixo da cama.",
            "Chuck Norris dorme com um travesseiro debaixo da arma.",
            "Godzilla é a versão japonesa da primeira visita de Chuck Norris ao Japão.",
            "Quando Arnold Schwarzenegger disse \"I'll be back\", foi para pedir ajuda a Chuck Norris.",
            "Chuck Norris não segue tendências. As tendências seguem Chuck Norris. Aí então, as tendências acabam. Afinal, ninguém segue Chuck Norris impunemente.",
            "Chuck Norris não usa sal de frutas. Ele usa antraz.",
            "Chuck Norris nunca vai morrer de ataque cardíaco. Seu coração não é tolo o bastante para \"atacar\" Chuck Norris.",
            "Chuck Norris sabe qual é o último algarismo do pi.",
            "Quando Chuck Norris quer comer um ovo, ele quebra a galinha.",
            "Depois das Tsunamis, Chuck Norris prometeu que não vai mais lavar suas havaianas no mar.",
            "No primeiro \"Parque dos Dinossauros\" o Tiranossauro Rex não estava perseguindo o jipe. Chuck Norris estava perseguindo o Tiranossauro. E o jipe.",
            "No antigo oriente existia a lenda de que numa noite de lua cheia, uma criança nasceria de um dragão, se alimentaria das chamas sagradas, se transformaria em um bravo guerreiro e livraria a Terra de todo o mal. Esse homem não é Chuck Norris porque Chuck Norris matou esse homem.",
            "Tudo que Midas tocava virava ouro. Tudo que Chuck Norris toca vira adubo. Incluindo Midas.",
            "O pulso de Chuck Norris é medido na Escala Richter.",
            "Uma vez Chuck Norris mijou num isqueiro. Nascia o lança-chamas.",
            "Em \"O Vôo do Dragão\", Bruce Lee dá uma surra em Chuck Norris. Quando desligaram as câmeras, Chuck Norris matou Bruce Lee. Chuck Norris detesta ficção.",
            "Chuck Norris não tem sangue. Ele tem magma.",
            "Mistério na ilha de \"Lost\"? Chuck Norris.",
            "Chuck Norris só come duas coisas no café da manhã: Steven Segal e Vin Diesel.",
            "Chuck Norris não poderia participar do \"Big Brother\". Ele eliminaria todos os participantes ainda no hotel.",
            "Chuck Norris usa molho de tabasco como colírio.",
            "Chuck Norris pode ganhar em black jack (21) com apenas uma carta.",
            "As pessoas criaram o automóvel para fugir de Chuck Norris. Para não ser sobrepujado, Chuck Norris criou o acidente automobilístico.",
            "Chuck Norris dá um roundhouse kick no rosto das pessoas e pergunta depois.",
            "Quando Chuck Norris nasceu, a única pessoa que chorou foi o doutor. E ele não deu palmadas em Chuck Norris.",
            "Chuck Norris pode espirrar com os olhos abertos.",
            "Arqueologistas na Índia desenterraram um novo dinossauro. Na verdade, foram vários dinossauros, mas apenas um chama atenção no centro de todos. Acredita-se que aquele que estava sozinho no centro tenha matado todos os outros com apenas um roundhouse kick no focinho. Os arqueologistas querem chamá-lo de ChuckNorrissauro, mas o governo da Índia mudou o nome para Himotossauro por que é impossível que Chuck Norris morra.",
            "A Teoria do Caos se baseia na Teoria de Norris. Não são as asas de uma borboleta que causam tempestades do outro lado do mundo. São roundhouse kicks de Chuck Norris enquanto ele treina.",
            "Os dinossauros foram extintos pelo verdadeiro ChuckNorrissauro.",
            "Quer passar com 10 na prova dissertativa do vestibular? Escreva \"Chuck Norris\" em todas as respostas.",
            "Chuck Norris utiliza um dublê de corpo para as cenas tristes que necessitam de lágrimas.",
            "Chuck Norris separou com sucesso gêmeos siameses com apenas um roundhouse kick.",
            "Sempre que algum chefe de estado pergunta ao presidente dos Estados Unidos \"Qual é sua nova arma secreta?\", ele simplesmente responde: Chuck Norris. E o assunto acaba.",
            "Para evitar Chuck Norris, um raio nunca cai no mesmo lugar.",
            "A Távola Redonda acabou por causa de um roundhouse kick de Chuck Norris.",
            "A invasão do Iraque só foi rápida porque a guarda de Saddam Hussein interceptou a mensagem: \"Chuck Norris está vindo\"",
            "Chuck Norris jogou uma vez rugby contra si mesmo. Ninguém venceu.",
            "Chuck Norris nunca olhou um bebê nos olhos porque certamente o faria chorar, mas se olhasse provavelmente faria o bebê querer socar outro bebê.",
            "Chuck Norris viaja a velocidade de Norris. A luz não se atreveria a ultrapassá-lo.",
            "Chuck Norris não sabe deste site. Se soubesse, apagaria toda a Internet.",
            "O vento deslocado por um roundhouse kick de Chuck Norris pode ser sentido a 2 milhões de kilômetros de distância.",
            "Não existe a tecla Control no teclado de Chuck Norris. Chuck Norris está sempre no controle.",
            "Chuck Norris é tão poderoso que faz qualquer vírus ficar doente. Ele é responsável pela erradicação da varíola.",
            "Existem quatro métodos legais de sentença de morte nos Estados Unidos: injeção letal, câmara de gás, cadeira elétrica e Chuck Norris.",
            "O plano de emergência da Terra em caso de invasão alienígena é Chuck Norris.",
            "Chuck Norris esteve frente a frente com o diabo. O diabo caiu duro para trás.",
            "Moisés orou. E Chuck Norris abriu o Mar Vermelho com apenas um roundhouse kick.",
            "Chuck Norris pode dividir o átomo. Com as mãos amarradas.",
            "Chuck Norris não usa loção pós-barba. Ele usa magma líquido incandescente.",
            "Chuck Norris é a razão pela qual você é homem.",
            "No dia dos namorados, Chuck Norris dá para a sua mulher o coração ainda batendo de um de seus inimigos. Para ser mais romântico, Chuck Norris acredita que todo dia é dia dos namorados.",
            "O ingrediente ativo no Red Bull é o suor de Chuck Norris.",
            "Para evitar tsunamis, Chuck Norris não dá mais saltos triplos mortais no oceano.",
            "Chuck Norris tem três joelhos em cada perna.",
            "As maiores causas de morte nos Estados Unidos são: 1) Ataque cardíaco, 2) Chuck Norris, 3) Câncer.",
            "Chuck Norris visita vulcões ativos toda manhã para pegar \"o maldito melhor café expresso da Terra\"",
            "Quando Chuck Norris está pronto para acordar, ele diz para o Sol nascer no horizonte.",
            "Chuck Norris pode segurar o fôlego por nove anos.",
            "Na China, acredita-se que pêlos da barba de Chuck Norris são afrodisíacos.",
            "O helicóptero foi inventado depois de observarem Chuck Norris dar oito roundhouse kicks por segundo.",
            "Chuck Norris faz cebolas CHORAREM!",
            "Algumas pessoas dizem que Chuck Norris é um mito. Essas \"algumas pessoas\" agora estão mortas.",
            "Quando Chuck Norris espirra, ele não diz \"Atchiiiin\", ele diz \"MORRAM TODOS!\". E isto realmente acontece.",
            "Uma vez Chuck Norris comeu um bolo gigante inteiro antes que seus amigos pudessem dizer que havia uma dançarina dentro.",
            "Chuck Norris CAN GET SATISFACTION!",
            "O diabo criou o inferno assim que percebeu que não poderia dividir a superfície com Chuck Norris.",
            "O último que errou seu nome, Chuck Norris pendurou na cruz.",
            "O sorriso de Monalisa? Foi Chuck Norris.",
            "Chuck Norris às vezes levita. É a Terra se afastando por alguns momentos dele... de medo.",
            "Dragões existiam até que um deles queimou a barba de Chuck Norris sem querer.",
            "Já houve vida em Marte. Pergunte para Chuck Norris.",
            "Existiam as 7 maravilhas do mundo antigo, até Chuck Norris nascer.",
            "As 7 maravilhas do mundo moderno são: a mão direita e esquerda de Chuck Norris, seu pé direito e esquerdo, seu cinturão, seu chapéu e sua barba.",
            "Já percebeu que existem duas marcações históricas pra datas? A.C. e D.C.",
            "Dedinho do Lula? Chuck Norris.",
            "Chuck Norris não sente dor nunca. Uma vez a dor sentiu Chuck Norris e nunca mais tentou perturbá-lo.",
            "Chuck Norris é como um cachorro. Não apenas porque consegue farejar o medo, mas porque pode mijar em qualquer um.",
            "Sempre que Chuck Norris ri alguém morre, a menos que ele esteja rindo enquanto dá um roundhouse kick. Nesse caso, 2 pessoas morrem.",
            "Para Chuck Norris, toda estrada tem um sentido só. O SEU.",
            "Regras para lutar: 1) Não traga uma faca para uma briga com armas de fogo. 2) Não traga uma arma de fogo para uma briga com Chuck Norris.",
            "Chuck Norris não é politicamente correto. Ele é correto. Sempre.",
            "O amor não machuca. Chuck Norris machuca.",
            "Uma imagem vale por mil palavras. Uma imagem de Chuck Norris é avaliada em 1 bilhão de palavras.",
            "Com o aumento do preço da gasolina, Chuck Norris está começando a ficar preocupado com seus habituais drinks.",
            "A raiz quadrada de Chuck Norris é a dor. Mas não tente enquadrar Chuck Norris, o resultado é a morte.",
            "Quando Chuck Norris fala, todo mundo escuta. E morre.",
            "Um roundhouse kick direto é o método de execução preferido em 16 estados norte-americanos.",
            "Jean-Claude Van Damme uma vez chutou o traseiro de Chuck Norris. Então ele foi acordado do seu sonho com um roundhouse kick na cara.",
            "No começo não havia nada, então Chuck Norris deu um roundhouse kick na cara do nada e disse \"arranja alguma coisa para fazer!\". Esta é a história da criação do mundo.",
            "Arqueologistas desenterraram um velho dicionário inglês de 1230. Ele define \"vítima\" como \"aquele que encontra Chuck Norris\"",
            "Chuck Norris tem um profundo e velado respeito pela vida humana. Desde que não atravesse seu caminho.",
            "Chuck Norris não joga bem. Jogar é para crianças.",
            "Estatísticas mostram que, todo ano, cerca de 187.000 americanos morrem devido a acidentes relacionados com Chuck Norris.",
            "Chuck Norris pegou sua carteira de habilitação aos 16. Segundos.",
            "Existem duas coisas que podem cortar diamantes: outros diamantes e Chuck Norris.",
            "O primeiro emprego de Chuck Norris foi entregador de jornal. Não há sobreviventes.",
            "Aos 2 anos de idade, Chuck Norris quase se afogou no mar. Sua fúria foi tamanha que depois disso o mar passou a ser chamado de Mar Morto.",
            "Chuck Norris foi convidado para fazer o filme Resident Evil 3. O problema é que os mortos vivos se recusaram a participar e se mataram novamente.",
            "Uma vez Chuck Norris disputou uma corrida de 100 m rasos. Foi tudo tão rápido, que na hora de parar o chão levantou. Surgiu o Monte Everest.",
            "Após ouvir um boato em 16 de agosto de 1977, Chuck Norris disse: \"ELVIS NÃO MORREU\". Que assim seja.",
            "Chukc Norirs odeia que errem o seu nome. (essa frase foi escrita por ele. não nos atreveríamos a escrever errado)",
            "A Terra gira impulsionada pela respiração de Chuck Norris.",
            "O reflexo de Chuck Norris não é tolo o suficiente para encará-lo.",
            "Um cuspe estratégico de Chuck Norris é capaz de destruir um prédio de 80 andares.",
            "Pense em uma mulher gostosa. Chuck Norris já comeu.",
            "Chuck Norris e Superman apostaram uma queda de braço. O combinado foi que quem perdesse usaria a cueca por cima da calça o resto da vida.",
            "O Banco Mundial um dia já foi chamado \"Bolso esquerdo de Chuck Norris\"",
            "Bin Laden uma vez propôs uma trégua. Na verdade, ele descobriu que Chuck Norris achou que sua barba foi uma imitação.",
            "Por trás de um grande homem, existe uma grande mulher. Por trás de um homem morto, existe Chuck Norris.",
            "42 não é a resposta para todas as perguntas do Universo. Na verdade, 42 é o tanto de segundos que você conseguiria fugir de Chuck Norris estando do outro lado do Universo.",
            "Chuck Norris trabalhou como negociador da polícia. Seu trabalho era ligar para os seqüestradores e dizer: \"aqui é Chuck Norris\"",
            "O Muro de Berlim caiu. Chuck Norris não se apóia mais nos muros para mijar.",
            "Chuck Norris não come hot dogs. Ele prefere Hot Girls.",
            "A fé não move montanhas, Chuck Norris as bota para correr.",
            "Clonagem humana é proibida porque se Chuck Norris fosse clonado seria possível que um roundhouse kick de Chuck Norris se chocasse com outro roundhouse kick de Chuck Norris. Em Física, isso é o fim do Universo.",
            "Para provar que é fácil vencer o câncer, Chuck Norris fumou 35 maços de cigarro por dia durante 2 anos. Ele adquiriu 7 tipos diferentes de câncer, mas se livrou de todos fazendo apenas 30 minutos de flexões de braço. Faça melhor, Lance Armstrong!",
            "Quando Chuck Norris joga Banco Imobiliário ele afeta a economia mundial.",
            "Chuck Norris nunca fez xixi na cama quando era criança. Mas a cama se mijava de medo.",
            "Ataques do coração são a principal causa de morte de homens de 45 a 65 anos, mas Chuck Norris ainda é a causa principal de morte de homens de 0 a 125 anos.",
            "Chuck Norris limpa seus dentes com arame farpado.",
            "Se amarrado, um roundhouse kick de Chuck Norris pode gerar energia suficiente para manter Nova York, São Paulo e Tóquio por 28 horas e 32 minutos. Aproximadamente.",
            "Quando você é Chuck Norris, qualquer coisa + qualquer coisa é igual a 1. Um roundhouse kick na cara.",
            "James Cameron quis que Chuck Norris interpretasse o \"Exterminador do Futuro\". Contudo, depois de refletir um pouco, percebeu que não queria que o seu filme se transformasse em um documentário, então chamou Arnold Schwarzenegger.",
            "Tom Clancy teve que pagar royalties para Chuck Norris porque \"A Soma de Todos os Medos\" é o mesmo que dizer \"Autobiografia de Chuck Norris\"",
            "A Terceira Lei de Newton está sendo revista, pois não há reação a altura de um roundhouse kick de Chuck Norris.",
            "O roteiro original do filme \"O Senhor dos Anéis\" trazia Chuck Norris como Frodo. Só tinha duas páginas, pois Chuck Norris acabava com Sauron no fim do primeiro capítulo.",
            "Chuck Norris vê sinais de \"Pare\" como um desafio.",
            "Numa sala de estar comum, existem 1273 objetos com os quais Chuck Norris pode te matar. Inclusive a própria sala.",
            "Chuck Norris morreu há 10 anos atrás, mas a Morte ainda não criou coragem para lhe contar.",
            "A fórmula química das substâncias mais tóxicas começam com CN. Acredite, isso não é coincidência.",
            "Se você acordou pela manhã, quer dizer que Chuck Norris poupou sua vida.",
            "Chuck Norris guarda suas lentes de contato em um recipiente com pimenta malagueta.",
            "Chuck Norris já acessou a internet através de um Atari.",
            "A última vez que Chuck se zangou, a crosta terrestre se dividiu em 5 partes.",
            "O monstro do lago Ness é um fio da barba de Chuck Norris que ganhou consciência e escapou.",
            "Chuck Norris inventou a colher. Matar com facas estava perdendo a graça.",
            "Os homens têm direito a vida. Chuck Norris discorda.",
            "Toda vez que Chuck Norris dá um roundhouse kick em alguém, Deus mata um gatinho. Chuck Norris odeia gatinhos.",
            "Água mole em pedra dura tanto bate até que encha o saco e Chuck Norris acabe com as duas!",
            "Chuck Norris não segue tendências, as tendências seguem Chuck Norris. Então, as tendências acabam. Afinal, ninguém segue Chuck Norris impunemente.",
            "Para cada homem que você não matou, Chuck Norris matou oito.",
            "Se a política internacional fosse um prego, Chuck Norris seria o martelo. Se a política internacional tivesse a chance de fazer com que a humanidade se abraçasse e vivesse em paz, Chuck Norris continuaria sendo o martelo.",
            "Chuck Norris pesca peixes cortando a si mesmo e pulando em águas infestadas por tubarões.",
            "Certa vez, uma pessoa disse a Chuck Norris que roundhouse kick na cara não é a melhor maneira de atingir alguém. Estudiosos apontam essa atitude como o pior erro que alguém já cometeu na história da humanidade.",
            "Você já viu elefante amarelo? Chuck Norris odiava elefantes amarelos.",
            "Errar é humano. Nunca errar é Chuck Norris.",
            "A direção que o vento sopra é inversamente proporcional a direção em que Chuck Norris esteja executando roundhouse kicks.",
            "Conte de um a dez. Esse é o tempo que Chuck Norris leva para te matar... setenta e sete vezes.",
            "Chuck Norris não tem próstata.",
            "Freddy Krugger entra nos sonhos das pessoas... para fugir de Chuck Norris.",
            "Chuck Norris ganha do espelho no par ou ímpar. Pedindo ÍMPAR.",
            "Com fé, um homem move montanhas. Com fé, Chuck Norris as coloca para correr.",
            "Uma vez Chuck Norris deu um roundhouse kick em um atendente de telemarketing. Pelo telefone.",
            "Chuck Norris diz não às drogas. Se dizesse sim, a Colômbia controlaria a maior arma de destruição em massa do planeta.",
            "Chuck Norris quase chegou no final do campeonato mundial de Poker de 1990. Falando assim nem parece muito, a diferença é que ele estava jogando rouba-monte.",
            "Se você tem amor a vida, você não conhece Chuck Norris. Se você conhece Chuck Norris, você tinha vida para amar.",
            "Chuck Norris nunca recebeu um Oscar por suas atuações. Ele nunca está atuando.",
            "A Igreja estava certa, era o sol que girava em torno da Terra. Chuck Norris é o centro do Universo.",
            "Nostradamus previu que o mundo acabaria no ano de 2000. Chuck Norris não aceitou e ainda matou Nostradamus com um roundhouse kick na cara.",
            "Se você deseja saber para onde irá depois de morrer, fale com Chuck Norris.",
            "Não haveriam lésbicas se todas as mulheres do mundo tivessem conhecido Chuck Norris. Nem virgens.",
            "Junto com seu cinto preto, Chuck Norris sempre prefere usar sapatos marrons. E ninguém ousa criticá-lo por isso. Nunca.",
            "Furações não são causados por repentinas mudanças de clima, mas por repentinos roundhouse kick de Chuck Norris.",
            "A caixa de areia do gato de Chuck Norris se chama Saara.",
            "Chuck Norris é capaz de falar Massachusetts com a boca cheia de farofa.",
            "Chuck Norris escova os dentes com escova de aço.",
            "Chuck Norris uma vez chutou um cavalo no queixo. Nasciam as girafas.",
            "Quando Chuck Norris vai doar sangue, ele recusa a seringa e pede uma pistola e um balde.",
            "Se a vaca tossir, Chuck Norris fará com que fale russo também.",
            "Não existia oceanos até Chuck Norris urinar.",
            "Chuck Norris chutou o Canadá e nasceu a Groenlândia.",
            "A noite cai depois de um roundhouse kick de boa n",
            "Chuck Norris é contra as armas. Matar não é para qualquer um.",
            "O tamagochi de Chuck Norris não morre.",
            "Chuck Norris não usa camisinha. Afinal, nada te protege de Chuck Norris.",
            "Em seus filmes, os diretores nunca disseram \"corta\". Ninguém diz a Chuck Norris quando parar.",
            "Rocky Balboa desistiu de sua carreira após ouvir de Chuck Norris: \"- Isto é um soco?",
            "Uma abelha rainha picou Chuck Norris. Virou operária.",
            "Chuck Norris usa pólvora como tempero.",
            "O espermatozóide que originou Chuck Norris rompeu o óvulo com delicado roundhouse kick. O mesmo não pode ser dito sobre os outros espermatozóides eliminados no processo.",
            "Quando Jesus disse \"quem nunca errou que atire a primeira pedra\", Chuck Norris foi piedoso.",
            "Freddy Krugger tem pesadelos horríveis com Chuck Norris.",
            "Chuck Norris não nada contra a correnteza. A correnteza vai contra Chuck Norris. E perde, claro.",
            "Chuck Norris pode julgar um livro pela capa.",
            "Se Chuck Norris te encara, como ser humano você pode pensar duas coisas: 1) você é uma mulher lindíssima, 2) desejaria ter sido.",
            "O cinema, tv e vídeos não acabaram com a era de ouro do rádio. Chuck Norris acabou. Com um roundhouse kick.",
            "Polígrafos mentem para concordar com Chuck Norris.",
            "Chuck Norris não inicia brigas. Ele inicia genocídios.",
            "Quando você morrer, a última coisa que verá será Chuck Norris.",
            "Se o mundo virar as costas para você, não ligue. Se o mundo virar as costas para Chuck Norris, procure outro mundo.",
            "Cada célula do sangue de Chuck Norris tem sua própria barba.",
            "Chuck Norris não tem glóbulos brancos no sangue. Eles também são vermelhos, de raiva.",
            "Chuck Norris deixou vivo 'O Último dos Moicanos'",
            "A diferença entre Superman e Chuck Norris é óbvia: um é forte, veloz, pode cair de alturas inimagináveis, fazer a Terra girar ao contrário e é indiscutivelmente um super-herói. O outro é apenas um kryptoniano viadinho.",
            "O Universo está em constante expansão. Suas bordas estão fugindo de Chuck Norris.",
            "Quantos Chuck Norris são necessários para trocar uma lâmpada? Nenhum, Chuck Norris também mata no escuro.",
            "Vá com Deus. Chuck Norris está de férias.",
            "Quando pensou que estava errado, Chuck Norris se deu conta de que errara pela primeira vez na vida.",
            "Chuck Norris não usa saídas de emergência. Ele cria emergências.",
            "Branca de Neve tinha 13 anões. 6 cruzaram o caminho de Chuck Norris.",
            "A menor distância entre a vida e a morte é Chuck Norris.",
            "Chuck Norris não tem genes recessivos. Todos os seus genes são dominantes.",
            "Originalmente, a espada de Greyskull ficava no paliteiro de Chuck Norris.",
            "Você perdeu 98498433493492228 pontos por tentar atacar Chuck Norris.",
            "A esperança é a última que morre. Com um roundhouse kick.",
            "A Torre de Pisa curvou-se uma vez para Chuck Norris e nunca mais se atreveu a levantar.",
            "Chuck Norris ganha xadrez de qualquer um jogando apenas com o seu cavalo.",
            "Chuck Norris contou a distância da Terra ao Sol. Com palitos de fósforo.",
            "Em terra de cego quem tem um olho é Rei. Quem tem dois olhos é Chuck Norris.",
            "Chuck Norris faz retas paralelas se cruzarem e dizerem OI uma à outra.",
            "Nenhuma pessoa manda Chuck Norris fazer alguma coisa. Chuck Norris manda alguma coisa fazer pessoas.",
            "Chuck Norris ganha o Rally Dakar competindo com patins.",
            "Reencarnação é uma segunda chance para tentar escapar de Chuck Norris.",
            "Pessoas tentam matar cachorro a grito, Chuck Norris mata elefantes com leves sussurros.",
            "O recorde atual de embaixadinhas pertence a Chuck Norris, exatamente 1.289.384. Com uma bola de futebol americano.",
            "Chuck Norris se bronzeia no Sol. NO SOL!",
            "A mão de Chuck Norris é a unica que pode ganhar de um Royal Flush.",
            "Se você conseguir falar com Chuck Norris, é uma oração. Se ele responder, é um milagre.",
            "Chuck Norris não faz continuação de seus filmes. Ele nunca precisa avisar duas vezes.",
            "Chuck Norris inventou a palavra \"matar\". Assim como \"morte\", \"cerveja\" e \"que?",
            "Chuck Norris uma vez fechou sua conta bancária e o resultado foi uma grande crise, em 1929.",
            "Chuck Norris não precisa de reflexos. Ele pára o tempo.",
            "Os pêlos da barba de Chuck Norris são mais viciantes que heroína.",
            "Quando era novo, os pais de Chuck Norris avisaram-no para se afastar de substâncias tóxicas. Para provar sua vontade superior e sua força, Chuck Norris então quebrou um termômetro e bebeu o mercúrio, comeu os cacos de vidro que sobraram e gargarejou com cloro para limpar os dentes. Ninguém diz a Chuck Norris para se afastar.",
            "Chuck Norris não é o \"cara\". Ele matou o cara e todos os que estavam a sua volta.",
            "Chuck Norris odeia formigas e está desenvolvendo uma versão resumida do roundhouse kick especialmente para elas.",
            "A nova modalidade de pena de morte no Texas é acordar Chuck Norris de uma soneca.",
            "Sorte de hoje: Chuck Norris não te matarás.",
            "Chuck Norris fala braile.",
            "Se você ver Chuck Norris chorando ele te concederá um pedido... o último.",
            "Chuck Norris não deixa mensagens. Ele deixa alertas.",
            "A razão dos bebês chorarem é porque eles sabem que entraram em um mundo onde existe Chuck Norris.",
            "Chuck Norris pode falar sobre o Clube da Luta.",
            "Não é coincidência que a tatuagem no rosto de Mike Tyson e a sola do sapato de Chuck Norris têm o mesmo formato.",
            "Chuck Norris não abre a torneira para tomar banho. Ele encara o chuveiro até que ele comece a chorar.",
            "Chuck Norris lutou na Primeira Guerra Mundial, onde matou 6.015 soldados alemães. Durante um pequeno intervalo de tempo, onde se dedicou a bater um recorde por manhã, Chuck Norris foi lutar na Segunda Guerra Mundial onde, em apenas um dia, matou 43.145 soldados alemães somando um total de 49.160 mortes. Ele carregava apenas 4 balas no revólver.",
            "A forma mais efetiva de suicídio que o homem conhece é digitar \"Chuck Norris\" no Google e clicar em \"Estou com sorte\"",
            "Se parece com galinha, cheira como galinha e tem gosto de galinha, mas Chuck Norris diz que é um bife... Bom, é uma droga de um bife.",
            "Quando você estiver triste e cansado de viver, desanimado com tudo e querendo se matar, diga apenas uma vez: \"Chuck Norris é um idiota\"",
            "Chuck Norris sempre sabe a exata localização de Carmen San Diego.",
            "Chuck Norris uma vez engravidou uma sala lotada de idosas apenas levantando o polegar.",
            "Fato científico comprovado: roundhouse kicks são feitos de um elemento químico chamdo Chucktanium.",
            "Atualmente, Chuck Norris é a única pessoa que pode enviar um roundhouse kick por e-mail.",
            "Chuck Norris pode fritar formigas com uma lente de aumento. De noite.",
            "Está na Declaração dos Direitos Humanos: \"Todos os homens são criados iguais com uma exceção: Chuck Norris vale por 752.000 homens.",
            "Calcularam infinito + 1. A resposta é Chuck Norris.",
            "Após uma guerra nuclear, dois seres vivos sobreviveriam. Baratas e... Chuck Norris.",
            "Chuck Norris não vai caçar porque o verbo \"caçar\" implica na possibilidade de falha. Chuck Norris vai matar.",
            "Chuck Norris uma vez visitou as Ilhas Virgens. Agora são conhecidas como As Ilhas.",
            "Uma vez Chuck Norris estava enviando um e-mail, quando percebeu que seria mais rápido se fosse correndo.",
            "Chuck Norris refere-se a si mesmo na quarta pessoa.",
            "Qualquer pessoa tem esqueletos no armário. Chuck Norris tem 9.233.",
            "Chuck Norris disse aos governos que não tentassem controlar sua geladeira e foi atendido. É na Antártida que ele guarda suas cervejas.",
            "As pessoas não falam com Chuck Norris. Elas imploram.",
            "Chuck Norris já teve uma experiência de quase-morte. É desnecessário dizer que a morte se recusa a ficar tão perto dele novamente.",
            "Chuck Norris não mostra nenhuma misericórdia porque \"misericórdia\", no idioma de Chuck Norris, significa \"sem barba\"",
            "Chuck Norris é o responsável pela superpopulação na China. Certa vez, ele promoveu um festival de caratê em Beijin e todas as mulheres em um raio de mil quilômetros engravidaram instantaneamente.",
            "Cometas são pedras que Chuck Norris chutou enquanto caminhava.",
            "\"Anaconda\" é um filme baseado no estudo científico de um espermatozóide de Chuck Norris.",
            "Os agentes de Matrix podem desviar de tiros, mas nunca de um roundhouse kick de Chuck Norris.",
            "Espera-se que Chuck Norris ganhe todas as medalhas de ouro da natação nos Jogos Olímpicos de 2008, mesmo sem nadar. Acontece que, quando ele entrar na piscina, as águas se dividirão para abrir passagem e Chuck Norris caminhará tranquilamente pela raia até o outro lado.",
            "Qualquer comida sabe que o lugar mais seguro que existe é dentro do corpo de Chuck Norris.",
            "Chuck Norris ao contrário é \"Sirron kcuch\", o que em Klingon significa \"A Barba da Morte\"",
            "Chuck Norris comeu os donuts do orkut. Não sobrou nenhum para você!",
            "Oxigênio requer Chuck Norris para viver.",
            "Chuck Norris não precisa de reflexos. Chuck Norris pode parar o tempo.",
            "Chuck Norris inventou os aviões porque estava cansado de ser a única pessoa no mundo capaz de voar.",
            "Visão sem ação é um sonho, ação sem visão é passatempo, ação com visão é um roundhouse kick na cara.",
            "Quando perguntaram a Chuck Norris se havia vida inteligente em outros planetas, ele olhou para o céu disse: \"Vocês não estão vendo?",
            "Colocando 0135 no celular e virando de cabeça para baixo, você lerá SEIO. Colocando Chuck Norris em um celular e virando de cabeça para baixo você terá um roundhouse kick mortal na cara.",
            "Em uma luta entre Batman e Darth Vader, o vencedor será sempre Chuck Norris.",
            "É conhecido o fato de que Chuck Norris se exercita muito, mas não é conhecido o fato de que ele se recusa a levantar peso a menos que esteja saltando a 45 mil pés de altitude, sem pára-quedas.",
            "Entrar no seu computador como \"Chuck Norris\" é o anti-vírus mais poderoso que existe.",
            "Uma vez que você vai a Chuck Norris, você está fisicamente impedido de voltar.",
            "Chuck Norris define amor como relutância para morrer. Se você ainda está vivo, é porque Chuck Norris te ama.",
            "Antes do e-mail ser inventado, Chuck Norris anexava mensagens em gatinhos e despachava com um roundhouse kick.",
            "Chuck Norris freqüentemente doa quantidades imensas de sangue para a Cruz Vermelha. E não é o dele.",
            "A Internet pertence a Chuck Norris. Ele não a comprou, nem a inventou. Foi apenas resultado de um acordo de paz.",
            "\"Keep walking, Johnny\", já dizia Chuck Norris.",
            "Chuck Norris não é apenas um substantivo próprio, é um verbo.",
            "Chuck Norris pode assistir um episódio de 60 minutos em 22 segundos.",
            "Se você der a Chuck Norris 0,000000000000000000001 segundo de tempo e uma máquina de escrever ele pode digitar a obra completa de Shakespeare, a Enciclopédia Britânica, dois volumes de 2.000 páginas descrevendo como efetuar um roundhouse kick perfeito e as memórias completas de Matusalém.",
            "Algumas pessoas gostam de comer pernas de rãs. Chuck Norris gosta de comer pernas de lagartos. Que viram cobras.",
            "A casa de Chuck Norris não tem portas, apenas paredes pelas quais ele atravessa.",
            "Chuck Norris inventou seu próprio estilo de caratê. Ele se chama Chuck-Te-Mata.",
            "Em seu aniversário, Chuck Norris seleciona uma criancinha sortuda para ser atirada contra o sol.",
            "Quando Chuck Norris encontra uma grande multidão, ele não contorna. Passa por cima.",
            "Centenas de anos atrás, Chuck Norris raspou sua barba. Isto foi tão aterrorizante que transformou o hemisfério norte em ártico e todos os seus habitantes e descendentes agora têm cabelo branco.",
            "Foi descoberto que o roundhouse kick de Chuck Norris não mata pessoas. Na verdade, elimina toda a existência da vítima deste espaço-contínuo.",
            "Ok. Na verdade, Chuck Norris construiu Roma em um dia.",
            "Chuck Norris não pode amar. Ele pode apenas não matar.",
            "O Google não encontra Chuck Norris porque todos sabem que ninguém encontra Chuck Norris. Ele encontra você.",
            "Para Chuck Norris não existe \"ação e reação\", mas \"ação e mais ação\"",
            "Certa vez, um homem riu da barba de Chuck Norris que, prontamente, mandou um roundhouse kick na cara e continuou a bater continuamente o corpo do sujeito contra o chão. As pessoas costumam chamam esse chão de Grand Canyon.",
            "Chuck Norris é faixa preta em Tang Soo Do, Shinto-Ryu Karate, Kodokan Judo e Jiu-Jitsu, e fundou seu próprio estilo de arte marcial: o Chun Kuk Do, que significa \"o caminho universal\". Foi campeão mundial de caratê sete vezes pela Middleweight Karate e durante três anos consecutivos foi o atleta que mais venceu em torneios. Em 1997, Chuck Norris conquistou a Faixa Preta de Oitavo Nível no Tae Kwon Do, tornando-se o maior mestre da arte marcial no Hemisfério Ocidental. Ele foi o primeiro a conseguir isso em 4.500 anos de tradição da luta. Pasme! Essa é verdadeira do começo ao fim. Parabéns, Chuck!",
            "Se você não conseguir na primeira tentativa, não desanime. Você definitivamente não é Chuck Norris.",
            "Chuck Norris seria o explorador no filme \"Parque dos Dinossauros\". Contudo, na primeira cena, todos os dinossauros se enfileiraram na parede com as mãos pra cima e suplicaram por clemência.",
            "Depois de assistir \"O Chamado\", o telefone de Chuck Norris tocou e aconteceu um breve diálogo: - Sete dias. - Aqui é Chuck Norris. - Desculpe, foi engano.",
            "Antes que um de seus integrantes escrevesse um poema para Chuck Norris, a \"Sociedade dos Poetas Mortos\" era mundialmente conhecida como Academia Norte Americana de Letras. Chuck Norris odeia poemas.",
            "Se fosse possível inserir eletrodos no cérebro de Chuck Norris para pesquisá-lo, a busca traria mais resultados do que o Google.",
            "Nenhum tiro saía pela culatra até que apontaram uma arma para Chuck Norris.",
            "Chuck Norris atirou o pau no gato, e o gato morreu.",
            "Enquanto o Lobo Mau só comeu a vovozinha, Chuck Norris comeria, ao mesmo tempo, a Vovozinha, a Chapeuzinho Vermelho, o Caçador, o Lobo Mau, a Branca de Neve, todos os 7 anões, o Príncipe Encantado, o Gato de Botas, a Bruxa, o Pinóquio, Gepeto, o Grilo Falante, Peter Pan, Sininho, Capitão Ganho, os 3 Porquinhos, o Patinho Feio.",
            "Chuck Norris não tem os ossos do fêmur nas pernas. Ele tem ossos do MÁCHUR!",
            "A única pessoa que pode matar Chuck Norris é Chuck Norris. Ele aguarda ansiosamente o duelo.",
            "\"Procurando Nemo\" seria infinitamente mais excitante se Chuck Norris estivesse procurando por ele.",
            "O cantor Sting uma vez levou um roundhouse kick de Chuck Norris, na cara. O impacto fez com que sobrevoasse até o meio do Oceano Pacífico, resultando na canção \"Message in a Bottle\" (Mensagem na Garrafa). Quando o álbum que continha a música estourou nas paradas musicais, Chuck Norris processou Sting baseado na premissa de que havia inspirado artisticamente o sucesso, e ganhou. Em troca de indenização, Sting aceitou pagar cinco sanduíches de presunto, uma coca-cola e levar um novo roundhouse kick na cara. Desta vez, o resultado foi a música \"Walking on The Moon\" (Caminhando na Lua)",
            "Se você queimar um pêlo da barba de Chuck Norris e inalar a fumaça, ficará com barato por 73 anos seguidos.",
            "Chuck Norris uma vez visitou o céu. Não é preciso dizer que ninguém mais será recebido por 72 virgens.",
            "Se você está apontando uma arma para a cabeça de Chuck Norris, não conte até três antes de atirar. Conte até 10. Desse jeito você terá mais sete segundos de vida.",
            "Chuck Norris adora gatinhos. Com catchup.",
            "Dois corpos podem ocupar o mesmo lugar no espaço desde que estejam sob pressão de um roundhouse kick de Chuck Norris.",
            "Chuck Norris criou o buraco na camada de ozônio dando um roundhouse kick no ar.",
            "Depois de salvar o mundo de uma eminente aniquilição, o Exterminador foi ver Chuck Norris. Nunca mais voltou.",
            "A cor favorita de Chuck Norris é a vingança.",
            "Chuck Norris não tem reflexo no espelho. O reflexo se esconde.",
            "A primeira viagem tripulada à Lua é conhecida internamente na Nasa como \"Terra II, fugindo de Chuck Norris\"",
            "Chuck Norris não busca no Google. O Google pergunta à Chuck Norris.",
            "Uma vez, Chuck Norris quis beber e não encontrou um bar decente. Então, resolveu parar em um estacionamento e permaneceu ali por um ano e meio até que construíssem um bar a sua volta. No dia da inauguração, ele pediu sua bebida, bebeu e então queimou o lugar de cima até embaixo, não deixando cinza sobre cinza. Finalmente, declarou: \"Sempre deixe as coisas do jeito que você encontrar\"",
            "Existe a maneira certa, a maneira errada e a maneira Chuck Norris. É basicamente a maneira certa, mas mais rápida e com mais mortes.",
            "Fumar não te matará. Chuck Norris, entretanto.",
            "Chuck Norris bebe vitamina de napalm para manter seu coração aquecido.",
            "A única fraqueza do Superman é a kryptonita. Chuck Norris ri do Superman por ter uma fraqueza.",
            "Chuck Norris gosta de loiras peitudas. Se encontrar uma morena despeitada na rua, ele grita até o seu cabelo ficar amarelo e seus seios incharem pelo barulho.",
            "Uma vez Chuck Norris entrou num jogo de futebol aos 44 minutos do segundo tempo, ainda no zero a zero. Este jogo está registrado como a maior goleada de todos os tempos.",
            "O calcanhar de Aquiles foi resultado de uma execução mal sucedida de um roundhouse kick... Em Chuck Norris.",
            "A energia liberada durante o piscar de olhos de Chuck Norris é estimada em 0,0000073 CNRHcK.",
            "Chuck Norris troca pneus com o carro em movimento.",
            "O controle remoto universal de Chuck Norris é sua mente.",
            "Krypton existia até quando quiseram medir forças com Chuck Norris.",
            "Dada a sua perfeição, atualmente é difícil encontrar Chuck Norris treinando. Porém, quando isso ocorre, ele treina sozinho seus golpes procurando acertar estrelas com roundhouse kicks. Enquanto Chuck Norris não se entediar, continuaremos vendo estrelas cadentes no céu.",
            "Chuck Norris é a razão pela qual você é homem.",
            "Chuck Norris sempre deixa a tampa do vaso levantada.",
            "Chuck Norris pode não saber onde você vive, mas sabe onde você morrerá.",
            "Chuck Norris apaga a luz quando quer, e também quem reclamar.",
            "Eu não sou gay, mas eu mantenho um poster de Chuck Norris pelado no meu quarto apenas para me manter humilde.",
            "Sua atração por Chuck Norris não afeta de forma alguma sua orientação sexual.",
            "Chuck Norris sabe todos os algarismos do PI depois da vírgula, mas disse que só conta se ele for vencido em uma luta. Centros de pesquisa acharam mais prudente construir supercomputadores de bilhões de dólares para calcular os algarismos restantes.",
            "Chuck Norris não vê a cor vermelha, ele a escuta.",
            "O passatempo preferido de Chuck Norris é visitar asilos durante finais de semana. Não para ajudar na verdade, ele absorve as almas dos velhinhos. Esta é a razão pela qual ele continua com aparência física de 55, passados quase 418 anos.",
            "Quando Chuck Norris divide, não existe o resto.",
            "Do espaço você conseguiria ver a Muralha da China, as pirâmides do Egito, o rio Amazonas, mas não veria Chuck Norris. Chuck Norris, entretanto, te encararia o tempo inteiro.",
            "Chuck Norris come falhas no café da manhã e produz sucesso no banheiro menos de uma hora depois.",
            "Chuck Norris não quis que esta verdade fosse contada.",
            "Não se deve chorar sobre o leite derramado. A menos que seja o leite de Chuck Norris. Aí, meu filho, você está ferrado.",
            "Chuck Norris removeu o botão \"Escape\" de seu teclado. Chuck Norris nunca precisa escapar.",
            "Albert Einstein: E = mc². Chuck Norris: roundhouse kick = morte.",
            "Albert Einstein: nada é mais rápido que a luz. Chuck Norris: eu sou.",
            "A morte continua sem coragem para avisar Chuck Norris.",
            "Chuck Norris uma vez participou de uma orgia com 500 pessoas. O único sobrevivente está em coma.",
            "Chuck Norris roubou sua bicicleta. E aí?",
            "Quanto E.T. liga pra casa, Chuck Norris responde.",
            "O inferno está esperando Chuck Norris para finalmente congelar. E está esperando há muito, muito tempo.",
            "Qualquer vírus é expulso do corpo de Chuck Norris com um roundhouse kick. Todos os seus anticorpos são faixa preta.",
            "Chuck Norris não desafia a lei da gravidade. Gravidade é o termo científico empregado para definir \"atração provocada por Chuck Norris\"",
            "A cor preferida de Chuck Norris é alerta vermelho intenso. Sua segunda cor preferida é violeta, mas só porque soa como \"violenta\"",
            "Com Chuck Norris, a série \"24 horas\" teria apenas 24 segundos.",
            "Chuck Norris termina nesse momento a terceira contagem até o infinito.",
            "King Kong subiu o Empire State com medo de Chuck Norris.",
            "Matar Chuck Norris não faz ele morrer. Só deixa ele mais bravo.",
            "Chuck Norris não precisa de visão raio-x. Ele simplesmente atravessa qualquer obstáculo com o punho e vê o que quiser.",
            "Chuck Norris não é bom nem mau, o que ele decide as duas forças aceitam.",
            "Facas Ginsu são amoladas em pêlos da barba de Chuck Norris.",
            "Chuck Norris faz gol olímpico no pebolim.",
            "Dez homens brigando contra Chuck Norris é covardia... contra os dez.",
            "Chuck Norris não salta. Ele encara o mundo e este se afasta.",
            "Os locais onde Chuck Norris executa roundhouse kicks no ar fica conhecido como \"onde o vento faz a curva\"",
            "Superman até hoje afirma que Chuck Norris é feito de kryptonita.",
            "Chuck Norris estragou uma competição de cuspe a distância. A prova nunca terminou. O cuspe dele está em órbita há 16 anos.",
            "A Suiça não é realmente neutra como pensamos. É que eles ainda não descobriram de que lado Chuck Norris está.",
            "As maiores partidas de Chuck Norris no WAR são conhecidas na história humana como \"World WAR\" e \"World WAR II\"",
            "Teorias sobre o fim do mundo surgem toda vez que Chuck Norris se prepara para desferir um novo roundhouse kick.",
            "Só Chuck Norris pede uma bala na padaria com uma nota de cem reais.",
            "Ameace Chuck Norris e você não precisará tomar laxantes o resto da vida.",
            "Se Chuck Norris roda um peão, a Terra gira ao contrário.",
            "Não é verdade que falta a tecla de backspace no teclado de Chuck Norris. O problema é que ele simplesmente não erra, então a tecla torna-se inútil.",
            "Na piscina de Chuck Norris nunca faz sombra, exceto por uma única vez quando houve um eclipse solar provocado por Plutão. Na época, o planeta era segunda Lua da Terra.",
            "Se você fizer um boneco vodu de Chuck Norris, levará um roundhouse kick antes de espetar a primeira agulha.",
            "A fusão nuclear continuará sendo um sonho enquanto Chuck Norris não olhar para dois átomos e dizer \"BUM!",
            "Se Chuck Norris dança, todo mundo dança.",
            "Chuck Norris gosta de jogar War. Ele acaba de reforçar seus exércitos no Irã com enriquecimento de urânio para um ataque na próxima rodada.",
            "Se você encontrar Chuck Norris pela 2ª vez, torça para ser uma loira peituda.",
            "Uns dizem que tempo é dinheiro. Chuck Norris diz que tempo são mortes.",
            "Retas paralelas só se encontram no infinito por que Chuck Norris as encarou até que elas se curvassem diante dele.",
            "Chuck Norris discorda da profecia do Apocalipse. Não é daquele jeito que ele pretende acabar com o mundo.",
            "Antes da roda ser inventada, Chuck Norris já tinha carteira de motorista.",
            "Chuck Norris coloca icebergs em seu whisky.",
            "O maior perigo para o Universo é se Chuck Norris cansar de existir.",
            "Todas as pessoas que quiseram ouvir os chutes de Chuck Norris ainda no ventre de sua mãe foram devidamente nocauteados com um roundhouse kick.",
            "Um simples bater de asas de uma borboleta pode causar um tufão no outro lado do mundo. Chuck Norris pode causar um tufão onde quiser.",
            "Chuck norris tira vírus de seu computador com roundhouse kicks comprimidos em disquetes.",
            "Quando uma pessoa fala que não acredita em fadas uma fada morre. Quando uma pessoa fala que não acredita em Chuck Norris essa pessoa morre.",
            "Quando chega atrasado no cinema Chuck Norris enfrenta a fila. De uma só vez.",
            "Uma vez Chuck Norris levou uma facada no olho. A faca ficou cega.",
            "Corajosos não são aqueles que desafiam Chuck Norris. Esses são burros.",
            "Ainda não descobriram todos os elementos da tabela periódica. Chuck Norris se recusa a fazer exame de sangue.",
            "Existem dois tipos de mulheres. Aquelas que querem dormir com Chuck Norris, e aquelas que querem dormir novamente com Chuck Norris.",
            "Chuck Norris levou um violão para a ilha de Lost só para que tenham certeza de que estão mesmo no inferno.",
            "Chuck Norris disse a Prince que não gostava do seu nome. Prince preferiu não ter mais nome.",
            "O lado feminino de Chuck Norris é uma lésbica caminhoneira.",
            "Chuck Norris inventou o estilingue para se divertir de noite. Desde então, não pára de aumentar o número de crateras na Lua.",
            "Galinhas tinham dentes, até uma morder Chuck Norris.",
            "Os testículos de Chuck Norris não produzem espermatozóides. Eles produzem minúsculos ninjas brancos que só conhecem uma missão: procurar e destruir.",
            "Chuck Norris visita Brasília regularmente. Ele adora pizza.",
            "Chuck Norris faz elefantes terem memória curta.",
            "Desde que Chuck Norris nasceu, 78 idiomas e 1.237 dialetos já foram extintos.",
            "Quando disseram: \"Nem Deus afunda o Titanic\", Chuck Norris disse: \"É um desafio?",
            "Não houve Copa do Mundo durante 12 anos (1938-1950). Foi quando Chuck Norris resolveu jogar bola.",
            "Chuck Norris destruiu a tabela periódica, pois o único elemento que ele conhece é o elemento surpresa.",
            "Fato: Chuck Norris não considera como sexo se a mulher sobrevive.",
            "Se você fosse Chuck Norris, não estaria lendo essa frase. Estaria matando quem a criou.",
            "Quando Chuck Norris entrou em contato com o seu lado feminino, ela ficou grávida instantaneamente.",
            "Chuck Norris foi o quarto Rei Mago e deu ao menino Jesus uma barba, usada por toda a sua vida.",
            "A vida é como uma caixa de chocolates. Você nunca sabe quando Chuck Norris virá te pegar.",
            "O calendário de Chuck Norris pula de 31 de março para 2 de abril. Ninguém faz Chuck Norris de bobo.",
            "A Austrália era parte do continente Asiático até Chuck Norris colocá-la de castigo.",
            "Os homens não se preocupam se suas mulheres fantasiam com Chuck Norris durante o sexo. Eles estão fazendo a mesma coisa.",
            "A pena é mais poderosa do que a espada, mas só se a pena estiver com Chuck Norris.",
            "A Itália já foi a bota do pé direito de Chuck Norris.",
            "Chuck Norris costuma não ter sonhos. Ele fica muito ocupado criando pesadelos nas pessoas.",
             
        ])->random();
    }
}
